// Code generated by go generate; DO NOT EDIT.
package youtube

// Source: https://raw.githubusercontent.com/yt-dlp/yt-dlp/master/yt_dlp/extractor/youtube.py
var clientInfos = []clientInfo{
	{
		name:            "web",
		priority:        30,
		requireJsPlayer: true,
		innertubeApiKey: "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "WEB",
				Clientversion: "2.20220801.00.00",
			},
		},
	},
	{
		name:            "web_embedded",
		priority:        28,
		requireJsPlayer: true,
		innertubeApiKey: "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "WEB_EMBEDDED_PLAYER",
				Clientversion: "1.20220731.00.00",
			},
		},
	},
	{
		name:            "web_music",
		priority:        27,
		requireJsPlayer: true,
		innertubeApiKey: "AIzaSyC9XL3ZjWddXya6X74dJoCTL-WEYFDNX30",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "WEB_REMIX",
				Clientversion: "1.20220727.01.00",
			},
		},
	},
	{
		name:            "web_creator",
		priority:        27,
		requireJsPlayer: true,
		innertubeApiKey: "AIzaSyBUPetSUmoZL-OhlxA7wSac5XinrygCqMo",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "WEB_CREATOR",
				Clientversion: "1.20220726.00.00",
			},
		},
	},
	{
		name:            "android",
		priority:        40,
		innertubeApiKey: "AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:        "ANDROID",
				Clientversion:     "17.31.35",
				Androidsdkversion: 30,
				Useragent:         "com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip",
			},
		},
	},
	{
		name:            "android_embedded",
		priority:        38,
		innertubeApiKey: "AIzaSyCjc_pVEDi4qsv5MtC2dMXzpIaDoRFLsxw",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:        "ANDROID_EMBEDDED_PLAYER",
				Clientversion:     "17.31.35",
				Androidsdkversion: 30,
				Useragent:         "com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip",
			},
		},
	},
	{
		name:            "android_music",
		priority:        37,
		innertubeApiKey: "AIzaSyAOghZGza2MQSZkY_zfZ370N-PUdXEo8AI",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:        "ANDROID_MUSIC",
				Clientversion:     "5.16.51",
				Androidsdkversion: 30,
				Useragent:         "com.google.android.apps.youtube.music/5.16.51 (Linux; U; Android 11) gzip",
			},
		},
	},
	{
		name:            "android_creator",
		priority:        37,
		innertubeApiKey: "AIzaSyD_qjV8zaaUMehtLkrKFgVeSX_Iqbtyws8",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:        "ANDROID_CREATOR",
				Clientversion:     "22.30.100",
				Androidsdkversion: 30,
				Useragent:         "com.google.android.apps.youtube.creator/22.30.100 (Linux; U; Android 11) gzip",
			},
		},
	},
	{
		name:            "ios",
		priority:        10,
		innertubeApiKey: "AIzaSyB-63vPrdThhKuerbB2N_l7Kwwcxj6yUAc",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "IOS",
				Clientversion: "17.33.2",
				Devicemodel:   "iPhone14,3",
				Useragent:     "com.google.ios.youtube/17.33.2 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)",
			},
		},
	},
	{
		name:     "ios_embedded",
		priority: 8,
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "IOS_MESSAGES_EXTENSION",
				Clientversion: "17.33.2",
				Devicemodel:   "iPhone14,3",
				Useragent:     "com.google.ios.youtube/17.33.2 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)",
			},
		},
	},
	{
		name:            "ios_music",
		priority:        7,
		innertubeApiKey: "AIzaSyBAETezhkwP0ZWA02RsqT1zu78Fpt0bC_s",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "IOS_MUSIC",
				Clientversion: "5.21",
				Devicemodel:   "iPhone14,3",
				Useragent:     "com.google.ios.youtubemusic/5.21 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)",
			},
		},
	},
	{
		name:     "ios_creator",
		priority: 7,
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "IOS_CREATOR",
				Clientversion: "22.33.101",
				Devicemodel:   "iPhone14,3",
				Useragent:     "com.google.ios.ytcreator/22.33.101 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)",
			},
		},
	},
	{
		name:            "mweb",
		priority:        0,
		requireJsPlayer: true,
		innertubeApiKey: "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "MWEB",
				Clientversion: "2.20220801.00.00",
			},
		},
	},
	{
		name:            "tv_embedded",
		priority:        18,
		requireJsPlayer: true,
		innertubeApiKey: "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
		innertubeContext: innertubeContext{
			Client: innertubeClient{
				Clientname:    "TVHTML5_SIMPLY_EMBEDDED_PLAYER",
				Clientversion: "2.0",
			},
		},
	},
}
